apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-webapp-deployment
  labels:
    app: go-webapp
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: go-webapp-container
          image: quay.io/gasoares/go-argocd-workshop:prod-97153a5310eaad50e9c82f74d25e7f845ea41a8c
